- name: generate slapd configuration for satellite
  template:
    src: slapd.conf
    dest: /etc/conf.d/slapd

- name: ldap should be able to read certificates
  user:
    name: ldap
    group: ldap
    groups: arcanum
    append: yes

- name: Recursively change group of letencrypt
  file:
    path: /etc/letsencrypt
    state: directory
    recurse: yes
    owner: root
    group: arcanum
    mode: g+r

- name: Recursively change group of letencrypt
  file:
    path: /etc/letsencrypt/{{ item }}
    state: directory
    mode: g+x
  loop:
    - live
    - archive

- name: Backup the ldap configuration every day
  become_user: consul
  cron:
    name: "backup ldap"
    special_time: "daily"
    job: "sudo slapcat -l {{ path_storage }}/backup/ldap/backup.ldif"
