- name: install pass packages
  package:
    name:
      - pass
      - cronie
  tags:
    - packages

- name: clone password store
  become_user: "{{ user }}"
  git:
    repo: git@github.com:DictumMortuum/pass.git
    dest: "/home/{{ user }}/.password-store"
    update: yes

- name: install password cronjob sync
  become_user: "{{ user }}"
  cron:
    name: "sync password store repo"
    minute: "0,20,40"
    job: "/usr/local/bin/dotctl sync-repo /home/{{ user }}/.password-store"
