- name: install gcc
  pacman: name=gcc

- name: install fontconfig
  pacman: name=fontconfig

- name: install libxft
  pacman: name=libxft

- name: install pkgconf
  pacman: name=pkgconf

- name: install libxinerama
  pacman: name=libxinerama
