- name: fetch dmenu
  git:
    repo: git://git.suckless.org/dmenu
    dest: "{{ thirdparty }}/dmenu"
    update: yes
  become_user: "{{ thirdparty_user }}"

- name: copy dmenu config
  template:
    src: config.h.j2
    dest: "{{ thirdparty }}/dmenu/config.h"
  become_user: "{{ thirdparty_user }}"

- name: make dmenu
  make:
    chdir: "{{ thirdparty }}/dmenu"
    target: install

- name: fetch st
  git:
    repo: https://github.com/DictumMortuum/st.git
    dest: "{{ thirdparty }}/st"
    update: yes
  become_user: "{{ thirdparty_user }}"

- name: make st
  make:
    chdir: "{{ thirdparty }}/st"
    target: install