- name: install xurls dependencies
  package:
    name:
      - go
      - fakeroot
      - binutils
      - file
  tags:
    - packages

- name: install xurls
  aur: name=xurls state=present
  when: ansible_distribution == "Archlinux"
  become_user: consul
  tags:
    - packages
