- name: install clipmenu
  pacman: name=clipmenu
  tags:
    - packages

- name: install clipnotify
  pacman: name=clipnotify
  tags:
    - packages

- name: create the clipmenud override directory for {{ user }}
  file: 
    name: "/home/{{ user }}/.config/systemd/user/clipmenud.service.d"
    state: directory
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"

- name: generate clipmenud override for machina
  copy:
    content: |
      [Service]
      Environment=DISPLAY=:1
    dest: "/home/{{ user }}/.config/systemd/user/clipmenud.service.d/override.conf"
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"

- name: enable clipmenud service
  become_user: "{{ user }}"
  systemd:
    name: clipmenud
    enabled: yes
    masked: no
    scope: user
    state: started
