#- name: create the clipmenud override directory for {{ user }}
#  file:
#    name: "/home/{{ user }}/.config/systemd/user/clipmenud.service.d"
#    state: directory
#    owner: "{{ user }}"
#    group: "{{ group | default(user) }}"

#- name: make sure that the clipmenud override directory for {{ user }} is deleted
#  file:
#    name: "/home/{{ user }}/.config/systemd/user/clipmenud.service.d"
#    state: absent

#- name: generate clipmenud override for machina
#  copy:
#    content: |
#      [Service]
#      Environment=DISPLAY=:1
#    dest: "/home/{{ user }}/.config/systemd/user/clipmenud.service.d/override.conf"
#    owner: "{{ user }}"
#    group: "{{ group | default(user) }}"

#- name: disable clipmenud service
#  become_user: "{{ user }}"
#  systemd:
#    name: clipmenud
#    enabled: no
#    masked: no
#    scope: user
#    state: stopped
