- name: install headless dependencies
  package:
    name:
      - ansible
      - "{{ package_ag | default('the_silver_searcher') }}"
      - youtube-dl
      - pass
      - "{{ package_vim }}"
      - gcc
      - fontconfig
      - "{{ package_libxft | default('libxft') }}"
      - pkgconf
      - "{{ package_libxinerama | default('libxinerama') }}"
      - tmux

- name: install headless archlinux dependencies
  package:
    name:
      - fzf # available for ubuntu 19.10+
      - cronie # ubuntu already has a cronjob package on the base install
  when: ansible_distribution == "Archlinux"

- name: install ansible-aur
  aur: name=ansible-aur-git state=present
  when: ansible_distribution == "Archlinux"
  become_user: "{{ user_thirdparty }}"
