- name: set the machine's swappiness value to 10
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: set locale (LANG) to en_US.UTF-8
  blockinfile:
    dest: /etc/locale.conf
    create: yes
    content: |
      LANG=en_US.UTF-8
    state: present

- name: update the /etc/hosts file
  blockinfile:
    dest: /etc/hosts
    content: |
      {% for item in groups['all'] %}
      {{ hostvars[item]['ansible_host'] }} {{ item }}
      {% endfor %}
    state: present

- name: add the pacman proxy at the top of the mirrorlist
  blockinfile:
    path: /etc/pacman.d/mirrorlist
    insertbefore: BOF
    content: |
      # pacman cache proxy
      Server = {{ pacman_proxy }}
