- hosts: sol
  become: yes
  roles:
    - { role: system/setup-nginx, servers: ["db", "gitea", "nextcloud", "servus", "admin", "pihole", "home", "admin", "grafana", "cyberchef", "mealie"]}
    - system/setup-servus
    - system/setup-asterisk
    - system/setup-gitea
