- hosts: desktop
  become: yes
  roles:
    - system/setup-common-desktop
    - system/setup-fonts
    - system/setup-suckless
    - system/setup-xurls
    - system/setup-qutebrowser
    - system/setup-i3
    - system/setup-gnome
    - system/setup-printers
    - { role: system/setup-gnome-user, user: "diabolus", group: "arcanum", system_account: "true" }
    - { role: system/setup-gnome-user, user: "dimitris", window_manager: "i3" }
    - { role: system/setup-gnome-user, user: "fofi" }
    - { role: system/setup-gnome-user, user: "manolis" }
    - { role: system/setup-gnome-user, user: "petrina" }
    - { role: system/setup-gnome-user, user: "theoni" }
    - { role: system/setup-brave, user: "diabolus", group: "arcanum" }
    - { role: system/setup-brave, user: "dimitris" }
    - { role: system/setup-brave, user: "fofi" }
    - { role: system/setup-brave, user: "manolis" }
    - { role: system/setup-brave, user: "petrina" }
    - { role: system/setup-brave, user: "theoni" }
    - { role: system/setup-clipmenud, user: "dimitris" }
    - { role: system/setup-vscode, user: "dimitris" }
