- hosts: all
  become: yes
  roles:
    - system/setup-thirdparty

- hosts: all
  become: yes
  become_user: dimitris
  roles: 
    - user/setup-dotfiles
    - user/setup-dotfiles-url
    - user/setup-notes
    - user/setup-pass

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - user/setup-dotfiles

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - user/setup-dotfiles

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - user/setup-dotfiles

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - user/setup-dotfiles

- hosts: all
  become: yes
  become_user: diabolus
  roles:
    - user/setup-dotfiles

- hosts: all
  become: yes
  become_user: consul
  roles:
    - user/setup-dotfiles
