- hosts: satellite
  become: yes
  roles:
    - system/setup-repository
    - system/setup-ldap-server
    - system/setup-nginx
    - system/setup-redis
    - system/setup-php
    - system/setup-gitea
    - system/setup-minidlna
    - system/setup-servus
    - system/setup-mariadb
    - system/setup-printers
