- hosts: desktop
  become: yes
  roles:
    - system/setup-common-desktop
    - system/setup-fonts
    - system/setup-suckless
    - system/setup-xurls
    - system/setup-qutebrowser
    - system/setup-i3
    - system/setup-gnome
    - system/setup-printers
