- hosts: satellite
  become: yes
  roles:
    - { role: system/setup-nginx, servers: ["satellite", "pacman", "repo"], enable_mirror: true }
    - system/setup-repository
    - system/setup-ldap-server
    - system/setup-redis
    - system/setup-php
    - system/setup-gitea
    - system/setup-minidlna
    - system/setup-servus
    - system/setup-mariadb
    - system/setup-printers
