- hosts: desktop
  become: yes
  become_user: dimitris
  roles:
    - user/setup-gnome
    - user/setup-vscode
    - user/setup-clipmenud

- hosts: desktop
  become: yes
  become_user: fofi
  roles:
    - user/setup-gnome

- hosts: desktop
  become: yes
  become_user: manolis
  roles:
    - user/setup-gnome

- hosts: desktop
  become: yes
  become_user: petrina
  roles:
    - user/setup-gnome

- hosts: desktop
  become: yes
  become_user: theoni
  roles:
    - user/setup-gnome

- hosts: desktop
  become: yes
  become_user: diabolus
  roles:
    - user/setup-gnome
