- hosts: sol
  become: yes
  roles:
    - { role: system/setup-nginx, servers: ["db", "extapi", "gitea", "nextcloud", "servus", "admin", "admin2", "pihole", "home", "admin", "grafana", "cyberchef", "mealie", "boardgames"]}
    - system/setup-servus
    # - system/setup-asterisk
    - system/setup-gitea
    - system/setup-cockpit
