- hosts: all
  become: yes
  roles:
    - { role: system/setup-dependencies, enable_headless: true }
    - system/setup-config
    - system/setup-thirdparty

- hosts: archlinux:archlinux_arm
  become: yes
  roles:
    - system/setup-pacman
    - { role: system/setup-user, user: "consul", group: "domus" }
    - { role: system/setup-user, user: "diabolus", group: "arcanum" }
    - { role: system/setup-user, user: "dimitris", enable_pass: true, enable_notes: true }
    - { role: system/setup-user, user: "fofi" }
    - { role: system/setup-user, user: "manolis" }
    - { role: system/setup-user, user: "petrina" }
    - { role: system/setup-user, user: "theoni" }

- hosts: ubuntu
  become: yes
  roles:
    - { role: system/setup-user, user: "draviolo", group: "orbis", enable_pass: true, enable_notes: true }

- hosts: all
  become: yes
  roles:
    - system/setup-ssh
    - system/setup-vim
    - system/setup-tmux
