- hosts: satellite
  become: yes
  roles:
    - system/setup-ldap-server
    - system/setup-nginx
    - system/setup-redis
    - system/setup-php
    - system/setup-nextcloud
    - system/setup-minidlna
    - system/setup-servus
