- name: clone password store
  become_user: "{{ user }}"
  git:
    repo: "{{ repo_pass }}"
    dest: "/home/{{ user }}/.password-store"
    update: yes

- name: install password cronjob sync
  become_user: "{{ user }}"
  cron:
    name: "sync password store repo"
    minute: "0,20,40"
    job: "/usr/local/bin/dotctl sync-repo /home/{{ user }}/.password-store"
