- name: install sudo
  pacman: name=sudo
  tags:
    - packages

- name: install ansible
  pacman: name=ansible
  tags:
    - packages

- name: install git
  pacman: name=git
  tags:
    - packages

- name: install tcl
  pacman: name=tcl
  tags:
    - packages

- name: install ag
  pacman: name=the_silver_searcher
  tags:
    - packages

- name: install youtube-dl
  pacman: name=youtube-dl
  tags:
    - packages

- name: install fzf
  pacman: name=fzf
  tags:
    - packages

- name: install cronie
  pacman: name=cronie
  tags:
    - packages

- name: install make
  pacman: name=make
  tags:
    - packages

- name: install patch
  pacman: name=patch
  tags:
    - packages
