- name: install zsh
  pacman: name=zsh
  tags:
    - packages

- name: clone pure
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ thirdparty }}/pure"
    update: yes
  become_user: consul

- name: clone zsh-async
  git:
    repo: https://github.com/mafredri/zsh-async.git
    dest: "{{ thirdparty }}/zsh-async"
    update: yes
  become_user: consul

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ thirdparty }}/zsh-syntax-highlighting"
    update: yes
  become_user: consul
