- name: copy dmenu config
  template:
    src: config.h.j2
    dest: "{{ thirdparty }}/dmenu/config.h"
  become_user: consul

- name: make dmenu
  make:
    chdir: "{{ thirdparty }}/dmenu"
    target: install

- name: make permutations
  make:
    chdir: "{{ thirdparty }}/permutations"
    target: install

- name: make st
  make:
    chdir: "{{ thirdparty }}/st"
    target: install
