groups:
  - name: AllInstances
    rules:
    - alert: InternetDown
      expr: modem_status{hostname="192.168.5.254"} == 0
      for: 10m
      annotations:
        title: 'Internet {{ $labels.instance }} down'
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 10 minutes.'
      labels:
        severity: 'critical'
    - alert: PiholeDown
      expr: pihole_status != 1
      annotations:
        title: 'Pihole down'
        description: 'Pihole is down'
      labels:
        severity: 'warning'
