- name: download the avatar for {{ user }}
  get_url:
    url: https://{{ domain }}/static/icons/{{ user }}
    dest: "/home/{{ user }}/.face"
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"

- name: copy {{ user }} avatar into gdm
  copy:
    src: "/home/{{ user }}/.face"
    dest: "/var/lib/AccountsService/icons/{{ user }}"
    remote_src: yes

- name: create the AccountService configuration for {{ user }}
  template:
    src: AccountsService.conf.j2
    dest: "/var/lib/AccountsService/users/{{ user }}"
