- name: install nginx
  pacman: name=nginx
  tags:
    - packages

#- name: install certbot
#  pacman: name=certbot
#  tags:
#    - packages

#- name: install certbot-nginx
#  pacman: name=certbot-nginx
#  tags:
#    - packages

- name: generate the sites configuration
  template:
    src: "{{ item }}.conf"
    dest: "/etc/nginx/{{ item }}.conf"
  loop: "{{ ['nginx'] + nginx_modules + [domain]}}"

- name: fetch static content
  git:
    repo: git@github.com:DictumMortuum/static.git
    dest: "{{ thirdparty }}/static"
    update: yes
  become_user: consul

- name: enable nginx service
  systemd:
    name: nginx
    enabled: yes
    masked: no
    state: started
