- name: install nginx
  pacman: name=nginx
  tags:
    - packages

#- name: install certbot
#  pacman: name=certbot
#  tags:
#    - packages

#- name: install certbot-nginx
#  pacman: name=certbot-nginx
#  tags:
#    - packages

- name: generate the sites configuration
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  loop:
    - nginx.conf
    - satellite.dictummortuum.com.conf
    - nextcloud.conf
    - transmission.conf
    - phpldapadmin.conf
    - phpmyadmin.conf
    - static.conf
    - gitea.conf
    - syncthing.conf
    - servus.conf
    - cups.conf

- name: fetch static content
  git:
    repo: git@github.com:DictumMortuum/static.git
    dest: "{{ thirdparty }}/static"
    update: yes
  become_user: consul

- name: enable nginx service
  systemd:
    name: nginx
    enabled: yes
    masked: no
    state: started
