- name: install nginx
  package:
    name:
      - nginx
      - pacman-contrib
  tags:
    - packages

- name: create the nginx module directory
  file:
    name: "/etc/nginx/{{ item }}"
    state: directory
  loop:
    - servers

- name: generate the x86_64_mirror server
  include: mirror.yml
  vars:
    mirror: "{{ x86_64_mirror }}"
  when: enable_mirror and enable_mirror | bool

- name: copy the nginx configuration
  template:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"

- name: create the servers
  template:
    src: "{{ item }}.conf"
    dest: "/etc/nginx/servers/{{ item }}.conf"
  loop: "{{ servers }}"

- name: enable nginx service
  systemd:
    name: nginx
    enabled: yes
    masked: no
    state: started
