- name: create domus directory
  file:
    name: "{{ path_thirdparty }}/{{ item }}"
    mode: "0775"
    owner: "{{ user_thirdparty }}"
    group: "{{ group_thirdparty }}"
    state: directory
  loop:
    - vim
    - vim/autoload
    - vim/plugged

- name: fetch the plug.vim script
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ path_thirdparty }}/vim/autoload/plug.vim"
    mode: "0775"
    owner: "{{ user_thirdparty }}"
    group: "{{ group_thirdparty }}"

#- name: install plugins with vim-plug
#  shell: vim +'PlugInstall --sync' +qall &> /dev/null
