- name: install cups
  package: name=cups
  tags:
    - packages

- name: add domus as a printer administrator group
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: '^SystemGroup'
    line: 'SystemGroup sys root domus'

- name: enable cups service
  systemd:
    name: cups
    enabled: yes
    masked: no
    state: started
