- name: install zerotier-one
  package: name=zerotier-one
  tags:
    - packages

- name: setup the zerotier interface name
  template:
    src: devicemap
    dest: /var/lib/zerotier-one/devicemap

- name: enable zerotier-one service
  systemd:
    name: zerotier-one
    enabled: yes
    masked: no
    state: started

- name: join the domus network
  shell: "zerotier-cli join {{ network_id | default('') }}"
  register: res
  changed_when: res.stdout != "200 join OK"

- name: get the zerotier node id
  shell: "zerotier-cli info | awk '{print $3}'"
  register: info
  changed_when: info.rc != 0

- name: check authorization status on zerotier
  local_action:
    module: uri
    url: "https://{{ path_servus }}/zerotier/member/{{ info.stdout }}"
  register: auth

# - name: authorize the zerotier node
#   local_action:
#     module: uri
#     url: "https://{{ path_servus }}/zerotier/member"
#     method: POST
#     body_format: form-urlencoded
#     body:
#       member: "{{ info.stdout }}"
#   when: auth.json.response.config.authorized is defined and auth.json.response.config.authorized != true | bool
