- name: install clipmenu
  pacman: name=clipmenu
  become_user: root
  tags:
    - packages

- name: install clipnotify
  pacman: name=clipnotify
  become_user: root
  tags:
    - packages

- name: enable clipmenud service
  systemd:
    name: clipmenud
    enabled: yes
    masked: no
    scope: user
    state: started
