storage: /mnt/nfsserver
tld: dictummortuum.com
domain: "satellite.{{ tld }}"
zeroconf_servus: satellite.local:1234
nvidia: false
dock: false

thirdparty: /opt/domus

user_thirdparty: consul

group_thirdparty: domus
group_nopasswd: nonsignum

font_sans: "Fira Sans"
font_mono: "Fira Code"

repo_pass: git@github.com:DictumMortuum/pass.git
repo_notes: git@github.com:DictumMortuum/notes.git
repo_dotfiles: git@github.com:DictumMortuum/dotfiles.git
repo_dotfiles_thirdparty: https://github.com/DictumMortuum/dotfiles.git
repo_i3_utils: https://github.com/DictumMortuum/i3-utils.git
repo_permutations: https://github.com/DictumMortuum/permutations.git
repo_static: git@github.com:DictumMortuum/static.git
repo_pure: https://github.com/sindresorhus/pure.git
repo_zsh_async: https://github.com/mafredri/zsh-async.git
repo_zsh_syntax_highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git

path_background: /usr/share/backgrounds/nord.png
