- name: install notable
  aur: name=notable-bin skip_installed=true
  tags:
    - packages

- name: generate notable dotfile
  template:
    src: notable.json.j2
    dest: "{{ ansible_env.HOME }}/.notable.json"
