- name: install vscode
  pacman: name=code
  become_user: root
  tags:
    - packages

#- name: install vscode extensions
#  shell: code --install-extension "{{ item }}"
#  loop:
#    - arcticicestudio.nord-visual-studio-code
#    - shaunlebron.vscode-parinfer
#    - sleutho.tcl
#    - EditorConfig.EditorConfig
