- name: clone notes
  git:
    repo: git@gitlab.com:DictumMortuum/notes.git
    dest: "{{ ansible_env.HOME }}/Notes"
    update: yes
    accept_hostkey: yes
    ssh_opts: "-F /dev/null"

- name: install notes cronjob sync
  cron:
    name: "sync notes repo"
    minute: "10,30,50"
    job: "{{ ansible_env.HOME }}/.local/bin/dotctl.sh sync-repo {{ ansible_env.HOME }}/Notes"
