- name: install avahi packages
  package:
    name:
      - avahi
      - nss-mdns
  tags:
    - packages

- name: enable the avahi service
  systemd:
    name: avahi-daemon
    enabled: yes
    masked: no
    state: started
