- name: install avahi
  pacman: name=avahi
  tags:
    - packages

- name: install nss-mdns
  pacman: name=nss-mdns
  tags:
    - packages

- name: enable the avahi service
  systemd:
    name: avahi-daemon
    enabled: yes
    masked: no
    state: started