- name: install php
  pacman: name=php
  tags:
    - packages

- name: install php-ldap
  pacman: name=php-ldap
  tags:
    - packages

- name: install php-redis
  pacman: name=php-redis
  tags:
    - packages

- name: install php-intl
  pacman: name=php-intl
  tags:
    - packages

- name: install php-imagick
  pacman: name=php-imagick
  tags:
    - packages

- name: install php-fpm
  pacman: name=php-fpm
  tags:
    - packages

- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=bz2' line='extension=bz2'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=curl' line='extension=curl'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=exif' line='extension=exif'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=gd' line='extension=gd'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=gettext' line='extension=gettext'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=iconv' line='extension=iconv'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=intl' line='extension=intl'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=ldap' line='extension=ldap'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=mysqli' line='extension=mysqli'
- lineinfile: dest=/etc/php/php.ini regexp='^;*zend_extension=opcache' line='zend_extension=opcache'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=pdo_mysql' line='extension=pdo_mysql'
- lineinfile: dest=/etc/php/php.ini regexp='^;*extension=zip' line='extension=zip'
- lineinfile: dest=/etc/php/php.ini regexp='^memory_limit = \\d+M' line='memory_limit = 512M'
- lineinfile: dest=/etc/php/php-fpm.d/www.conf line='env[PATH] = /usr/local/bin:/usr/bin:/bin'
- lineinfile: dest=/etc/php/conf.d/igbinary.ini regexp='^;*extension=igbinary.so' line='extension=igbinary.so'
- lineinfile: dest=/etc/php/conf.d/redis.ini regexp='^;*extension=redis' line='extension=redis'

- name: create the /etc/systemd/system/php-fpm.service.d/ directory
  file: dest="/etc/systemd/system/php-fpm.service.d/" state=directory

- name: enable php-fpm service
  systemd:
    name: php-fpm
    enabled: yes
    masked: no
    state: started
