- name: install php packages
  package:
    name:
      - php
      - php-ldap
      - php-redis
      - php-intl
      - php-imagick
      - php-fpm
  tags:
    - packages

- name: enable the bz2 php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=bz2'
    line: 'extension=bz2'

- name: enable the curl php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=curl'
    line: 'extension=curl'

- name: enable the exif php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=exif'
    line: 'extension=exif'

- name: enable the gd php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=gd'
    line: 'extension=gd'

- name: enable the gettext php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=gettext'
    line: 'extension=gettext'

- name: enable the iconv php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=iconv'
    line: 'extension=iconv'

- name: enable the intl php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=intl'
    line: 'extension=intl'

- name: enable the ldap php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=ldap'
    line: 'extension=ldap'

- name: enable the mysqli php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=mysqli'
    line: 'extension=mysqli'

- name: enable the opcache php zend extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*zend_extension=opcache'
    line: 'zend_extension=opcache'

- name: enable the pdo_mysql php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=pdo_mysql'
    line: 'extension=pdo_mysql'

- name: enable the zip php extension
  lineinfile:
    dest: /etc/php/php.ini
    regexp: '^;*extension=zip'
    line: 'extension=zip'

- name: increase the php memory limit to 512M
  ini_file:
    path: /etc/php/php.ini
    section: PHP
    option: memory_limit
    value: 512M

- name: set the PATH environment variable for php
  ini_file:
    path: /etc/php/php-fpm.d/www.conf
    section: www
    option: env[PATH]
    value: /usr/local/bin:/usr/bin:/bin

- name: enable the igbinary php extension
  ini_file:
    path: /etc/php/conf.d/igbinary.ini
    section: igbinary
    option: extension
    value: igbinary.so

- name: enable the redis php extension
  ini_file:
    path: /etc/php/conf.d/redis.ini
    section: null
    option: extension
    value: redis

- name: create the /etc/systemd/system/php-fpm.service.d/ directory
  file:
    dest: "/etc/systemd/system/php-fpm.service.d/"
    state: directory

- name: enable php-fpm service
  systemd:
    name: php-fpm
    enabled: yes
    masked: no
    state: started
