- name: install php packages
  package:
    name:
      - php
      - php-redis
      - php-intl
      - php-imagick
      - php-fpm
      - php-igbinary
  tags:
    - packages

- name: enable php extensions
  lineinfile:
    dest: /etc/php/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ php_extensions }}"

- name: increase the php memory limit to 2048M
  ini_file:
    path: /etc/php/php.ini
    section: PHP
    option: memory_limit
    value: 2048M

- name: set the PATH environment variable for php
  ini_file:
    path: /etc/php/php-fpm.d/www.conf
    section: www
    option: env[PATH]
    value: /usr/local/bin:/usr/bin:/bin

- name: enable the igbinary php extension
  ini_file:
    path: /etc/php/conf.d/igbinary.ini
    section: igbinary
    option: extension
    value: igbinary.so

- name: enable the redis php extension
  ini_file:
    path: /etc/php/conf.d/redis.ini
    section: null
    option: extension
    value: redis

- name: enable the imagick php extension
  ini_file:
    path: /etc/php/conf.d/imagick.ini
    section: imagick
    option: extension
    value: imagick

- name: create the /etc/systemd/system/php-fpm.service.d/ directory
  file:
    dest: "/etc/systemd/system/php-fpm.service.d/"
    state: directory

- name: generate php-fpm override systemctl configuration
  template:
    src: php-fpm-override.conf
    dest: /etc/systemd/system/php-fpm.service.d/override.conf

- name: enable php-fpm service
  systemd:
    name: php-fpm
    enabled: yes
    masked: no
    state: started
