nginx_modules:
  - cups
  - gitea
  - nextcloud
  - phpldapadmin
  - phpmyadmin
  - static
  - syncthing
  - transmission

armv7h_mirror:
  type: armv7h
  port: 8000
  servers:
    - http://mirror.archlinuxarm.org

x86_64_mirror:
  type: x86
  port: 9000
  servers:
    - http://ftp.cc.uoc.gr/mirrors/linux/archlinux
    - http://ftp.ntua.gr/pub/linux/archlinux
    - http://ftp.otenet.gr/linux/archlinux
    - http://archlinux.vi-di.fr
    - http://arch.serverspace.co.uk/arch
    - http://archlinux.honkgong.info

path_certificate: "/data/letsencrypt/fullchain.pem"
path_certificate_key: "/data/letsencrypt/privkey.pem"
path_php_fpm: "/run/php-fpm/php-fpm.sock"

enable_mirror: false
mirror: "{{ x86_64_mirror }}"
