- name: initialize dotfiles for {{ home }}
  command: git --git-dir="{{ git_dir }}" init
  args:
    creates: "{{ git_dir }}"
    chdir: "{{ home }}"

- name: check if remote exists
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" remote get-url domus
  register: dotfiles
  changed_when: dotfiles.stdout != thirdparty ~ "/dotfiles"
  failed_when: '"domus" not in dotfiles.stderr and dotfiles.stderr != ""'
  notify:
    - add the dotfiles remote url
    - fetch dotfiles
    - checkout master
    - set local master to track remote master branch
    - add the dotfiles origin url

- meta: flush_handlers

- name: pull latest dotfiles
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" pull domus master
  register: dotfiles
  changed_when: dotfiles.stdout != "Already up to date."

- name: create async.zsh link
  file:
    src: "{{ thirdparty }}/zsh-async/async.zsh"
    dest: "{{ ansible_env.HOME }}/.cache/zsh/async"
    state: link

- name: create pure.zsh link
  file:
    src: "{{ thirdparty }}/pure/pure.zsh"
    dest: "{{ ansible_env.HOME }}/.cache/zsh/prompt_pure_setup"
    state: link
