- name: setup the servus configuration
  template:
    src: servusrc.yml
    dest: /etc/conf.d/servusrc.yml
    mode: 0600
    owner: root
    group: root

- name: enable servus service
  systemd:
    name: servus
    enabled: yes
    masked: no
    state: restarted
