- name: fetch servus
  git:
    repo: git@github.com:DictumMortuum/servus.git
    dest: "{{ path_thirdparty }}/servus"
    update: yes
  become_user: consul

- name: make servus
  make:
    chdir: "{{ path_thirdparty }}/servus"
    target: install

- name: copy servus systemd service file
  template:
    src: servus.service
    dest: /etc/systemd/system/servus.service

- name: enable servus service
  systemd:
    name: servus
    enabled: yes
    masked: no
    state: started

- name: check the router endpoint every so often
  become_user: consul
  cron:
    name: "check router"
    minute: "*/3"
    job: curl "https://{{ path_servus }}/router?ip=192.168.2.254"

- name: update telegram users
  become_user: consul
  cron:
    name: "check for new telegram users"
    minute: "*/10"
    job: curl "https://{{ path_servus }}/boardgames/prices/new"

- name: create messages
  become_user: consul
  cron:
    name: "create messages"
    minute: "*/20"
    job: curl "https://{{ path_servus }}/boardgames/prices/msg"

- name: check stores
  become_user: consul
  cron:
    name: check {{ item.name }}
    hour: "{{ item.hour }}"
    minute: "5"
    job: curl "https://{{ path_servus }}/boardgames/{{ item.name }}"
  loop:
    - name: gamerules
      hour: 0
    - name: vgames
      hour: 1
    - name: fantasygate
      hour: 2
    - name: mysterybay
      hour: 3
    - name: boardgameprices
      hour: 4
    - name: kaissa
      hour: 5

- name: notify via telegram on boardgameprices
  become_user: consul
  cron:
    name: "notify price reductions"
    hour: "*/4"
    minute: "0"
    job: curl "https://{{ path_servus }}/boardgames/prices/notify"

- name: sync the tcalendar entries with nextcloud
  become_user: consul
  cron:
    name: "sync calendars"
    minute: "*/5"
    job: curl "https://{{ path_servus }}/calendar/sync"
