- name: setup the servus configuration
  template:
    src: "{{ item }}"
    dest: /etc/conf.d/{{ item }}
    mode: 0600
    owner: root
    group: root
  loop:
    - servusrc.yml
    - modem_a.yml
    - modem_b.yml
    - modem_c.yml

- name: enable servus service
  systemd:
    name: servus
    enabled: yes
    masked: no
    state: restarted
