- name: fetch servus
  git:
    repo: git@github.com:DictumMortuum/servus.git
    dest: "{{ path_thirdparty }}/servus"
    update: yes
  become_user: consul

- name: make servus
  make:
    chdir: "{{ path_thirdparty }}/servus"
    target: install

- name: copy servus systemd service file
  template:
    src: servus.service
    dest: /etc/systemd/system/servus.service

- name: enable servus service
  systemd:
    name: servus
    enabled: yes
    masked: no
    state: started

- name: check the router endpoint every so often
  become_user: consul
  cron:
    name: "check router"
    minute: "*/3"
    job: curl "https://{{ path_servus }}/router?ip=192.168.2.254"

- name: check the boardgameprices.co.uk endpoint every so often
  become_user: consul
  cron:
    name: "check boardgameprices"
    hour: "*/4"
    job: curl "https://{{ path_servus }}/boardgames/prices"
