- name: setup the servus configuration
  template:
    src: "{{ item }}"
    dest: /etc/conf.d/{{ item }}
    mode: 0600
    owner: consul
    group: root
  loop:
    - servusrc.yml

# - name: enable servus service
#   systemd:
#     name: servus
#     enabled: yes
#     masked: no
#     state: restarted
