#- name: install vscode extensions
#  shell: code --install-extension "{{ item }}"
#  loop:
#    - arcticicestudio.nord-visual-studio-code
#    - shaunlebron.vscode-parinfer
#    - sleutho.tcl
#    - EditorConfig.EditorConfig

- name: check that the config folder exists
  stat:
    path: "/home/{{ user }}/.config/Code\ -\ OSS"
  register: res

- name: create Code - OSS to Code settings.json symlink
  file:
    src: "/home/{{ user }}/.config/Code/User/settings.json"
    dest: "/home/{{ user }}/.config/Code - OSS/User/settings.json"
    force: yes
    state: link
    follow: no
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"
  when: res.stat.exists == true
