route:
  group_by: ['alertname']
  group_wait: 10s
  receiver: 'default'
  routes:
    - receiver: 'ntfy'
      repeat_interval: 10s
      continue: true
    - receiver: 'router.reset'
      repeat_interval: 1h
      matchers:
        - alertname="InternetDown"
        - hostname="192.168.5.254"

receivers:
  - name: 'default'
  - name: 'router.reset'
    webhook_configs:
      - url: 'https://servus.dictummortuum.com/router/reset'
        send_resolved: false
  - name: 'ntfy'
    webhook_configs:
      - url: 'https://servus.dictummortuum.com/ntfy'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
