php_extensions:
  - regexp: '^;*extension=bz2'
    line: 'extension=bz2'
  - regexp: '^;*extension=bcmath'
    line: 'extension=bcmath'
  - regexp: '^;*extension=gmp'
    line: 'extension=gmp'
  - regexp: '^;*extension=curl'
    line: 'extension=curl'
  - regexp: '^;*extension=exif'
    line: 'extension=exif'
  - regexp: '^;*extension=gd'
    line: 'extension=gd'
  - regexp: '^;*extension=gettext'
    line: 'extension=gettext'
  - regexp: '^;*extension=iconv'
    line: 'extension=iconv'
  - regexp: '^;*extension=intl'
    line: 'extension=intl'
  - regexp: '^;*extension=ldap'
    line: 'extension=ldap'
  - regexp: '^;*extension=mysqli'
    line: 'extension=mysqli'
  - regexp: '^;*zend_extension=opcache'
    line: 'zend_extension=opcache'
  - regexp: '^;*extension=pdo_mysql'
    line: 'extension=pdo_mysql'
  - regexp: '^;*extension=zip'
    line: 'extension=zip'
