- name: install fontconfig
  pacman: name=fontconfig
  tags:
    - packages

- name: install fira sans fonts
  pacman: name=ttf-fira-sans
  tags:
    - packages

- name: install fira code fonts
  pacman: name=otf-fira-code
  tags:
    - packages

- name: set local.conf font config
  template:
    src: local.conf.j2
    dest: /etc/fonts/local.conf

#sudo ln -s /etc/fonts/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d
#sudo ln -s /etc/fonts/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d
#sudo ln -s /etc/fonts/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d

#/etc/profile.d/freetype2.sh
#export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
