- name: install fontconfig
  pacman: name=fontconfig
  tags:
    - packages

- name: install fira sans fonts
  pacman: name=ttf-fira-sans
  tags:
    - packages

- name: install fira code fonts
  pacman: name=otf-fira-code
  tags:
    - packages

- name: set local.conf font config
  template:
    src: local.conf.j2
    dest: /etc/fonts/local.conf

- name: enable fonts configs
  file:
    src: /etc/fonts/conf.avail/{{ item }}
    dest: /etc/fonts/conf.d/{{ item }}
    state: link
  loop:
    - 70-no-bitmaps.conf
    - 10-sub-pixel-rgb.conf
    - 11-lcdfilter-default.conf

- name: create the freetype2.sh script
  copy:
    dest: /etc/profile.d/freetype2.sh
    content: |
      export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
