#- name: install vscode extensions
#  shell: code --install-extension "{{ item }}"
#  loop:
#    - arcticicestudio.nord-visual-studio-code
#    - shaunlebron.vscode-parinfer
#    - sleutho.tcl
#    - EditorConfig.EditorConfig

- name: check that the config folder exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/Code\ -\ OSS"
  register: res

- name: create Code - OSS to Code settings.json symlink
  file:
    src: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    dest: "{{ ansible_env.HOME }}/.config/Code - OSS/User/settings.json"
    force: yes
    state: link
  when: res.stat.exists == true
