- name: fetch permutations
  git:
    repo: "{{ repo_permutations }}"
    dest: "{{ path_thirdparty }}/permutations"
    update: yes
  become_user: "{{ user_thirdparty }}"

- name: make permutations
  make:
    chdir: "{{ path_thirdparty }}/permutations"
    target: install
