- include: dependencies.yml
  tags:
    - packages

- name: fetch i3-utils
  git:
    repo: https://github.com/DictumMortuum/i3-utils.git
    dest: "{{ thirdparty }}/i3-utils"
    update: yes
  become_user: consul

- name: make i3-utils
  make:
    chdir: "{{ thirdparty }}/i3-utils"
    target: install

- name: fetch permutations
  git:
    repo: https://github.com/DictumMortuum/permutations.git
    dest: "{{ thirdparty }}/permutations"
    update: yes
  become_user: consul

- name: make permutations
  make:
    chdir: "{{ thirdparty }}/permutations"
    target: install
