- name: fetch i3-utils
  git:
    repo: "{{ repo_i3_utils }}"
    dest: "{{ thirdparty }}/i3-utils"
    update: yes
  become_user: "{{ thirdparty_user }}"

- name: make i3-utils
  make:
    chdir: "{{ thirdparty }}/i3-utils"
    target: install

- name: fetch permutations
  git:
    repo: "{{ repo_permutations }}"
    dest: "{{ thirdparty }}/permutations"
    update: yes
  become_user: "{{ thirdparty_user }}"

- name: make permutations
  make:
    chdir: "{{ thirdparty }}/permutations"
    target: install
