- include: dependencies.yml
  tags:
    - packages

- name: install xkb-switch
  aur: name=xkb-switch state=latest
  become_user: consul
  tags:
    - packages

- name: fetch i3-utils
  git:
    repo: https://github.com/DictumMortuum/i3-utils.git
    dest: "{{ thirdparty }}/i3-utils"
    update: yes
  become_user: consul
  notify: make i3-utils

- name: fetch permutations
  git:
    repo: https://github.com/DictumMortuum/permutations.git
    dest: "{{ thirdparty }}/permutations"
    update: yes
  become_user: consul
  notify: make permutations
