- name: install cockpit
  package: name=cockpit
  tags:
    - packages

- name: create cockpit configuration
  template:
    src: config.conf
    dest: /etc/cockpit/cockpit.conf

- name: enable cockpit service
  systemd:
    name: cockpit
    enabled: yes
    masked: no
    state: restarted
