- name: create the steam directory
  file:
    name: "{{ path_steam }}"
    group: "{{ group_steam | default('steam') }}"
    mode: 'u=rwx,g=rwx,o=rx,g+s'
    state: directory
  when: enable_steam is defined and enable_steam | bool
