- name: add the dotfiles remote url
  become_user: "{{ dot_user }}"
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" remote add domus "{{ thirdparty }}/dotfiles"

- name: fetch dotfiles
  become_user: "{{ dot_user }}"
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" fetch domus master

- name: checkout master
  become_user: "{{ dot_user }}"
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" checkout --force master

- name: set local master to track remote master branch
  become_user: "{{ dot_user }}"
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" branch --set-upstream-to=domus/master master

- name: add the dotfiles origin url
  become_user: "{{ dot_user }}"
  command: git --git-dir="{{ git_dir }}" --work-tree="{{ home }}" remote add origin git@github.com:DictumMortuum/dotfiles.git
  register: dotfiles
  changed_when: dotfiles.rc == 0
  failed_when: '"origin" not in dotfiles.stderr and dotfiles.stderr != ""'
