- name: install nextcloud
  pacman: name=nextcloud
  tags:
    - packages

- name: install mariadb
  pacman: name=mariadb
  tags:
    - packages

- name: create the /etc/pacman.d/hooks directory
  file: dest="/etc/pacman.d/hooks" state=directory

- name: generate pacman database upgrade hook
  template:
    src: nextcloud.hook
    dest: /etc/pacman.d/hooks/nextcloud.hook

- name: generate php-fpm override systemctl configuration
  template:
    src: php-fpm-override.conf
    dest: /etc/systemd/system/php-fpm.service.d/override.conf
