- name: check that the brave default profile exists for {{ user }}
  stat:
    path: "{{ preferences_path }}"
  register: res

- name: get the current preferences of {{ user }}
  command: "cat '{{ preferences_path }}'"
  register: current_preferences
  when: res.stat.exists
  changed_when: False

- name: merge the preferences
  set_fact:
    preferences: "{{ current_preferences.stdout | from_json | combine( default_preferences, recursive=True ) }}"
  when: res.stat.exists

- name: upload the merged preferences for {{ user }}
  copy:
    content: "{{ preferences | to_json }}"
    dest: /tmp/{{ user }}.brave
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"
  when: res.stat.exists
  changed_when: False

- name: sort the keys of the resulting json
  shell: "cat /tmp/{{ user }}.brave | jq --sort-keys > /tmp/{{ user }}.brave.sorted"
  when: res.stat.exists
  changed_when: False

- name: set the merged preferences for {{ user }}
  copy:
    src: /tmp/{{ user }}.brave.sorted
    dest: "{{ preferences_path }}"
    owner: "{{ user }}"
    group: "{{ group | default(user) }}"
    remote_src: yes
  when: res.stat.exists
