- name: switch to xorg from wayland
  ini_file:
    path: "{{ path_gdm | default('/etc/gdm') }}/custom.conf"
    section: daemon
    option: WaylandEnable
    value: "false"

- name: create the user profile
  copy:
    dest: /etc/dconf/profile/gdm
    content: |
      user-db:user
      system-db:gdm

- name: create the conf system gdm db directory
  file:
    name: /etc/dconf/db/gdm.d
    state: directory

- name: create the gdm database
  template:
    src: gdm.j2
    dest: /etc/dconf/db/gdm.d/config
