- name: enable gdm service
  systemd:
    name: gdm
    enabled: yes
    masked: no
    state: started

- include: gnome-dconf.yml
- include: gnome-gdm.yml

- name: update dconf database
  shell: dconf update
