- name: install gnome
  pacman: name=gnome
  tags:
    - packages

- name: install psutils
  pacman: name=python-psutil
  tags:
    - packages

- name: install papirus theme
  pacman: name=papirus-icon-theme
  tags:
    - packages

- name: install dash to dock
  aur: name=gnome-shell-extension-dash-to-dock skip_installed=true
  become_user: consul
  tags:
    - packages

- name: enable passwordless login
  lineinfile:
    path: "/etc/pam.d/gdm-password"
    line: "auth sufficient pam_succeed_if.so user ingroup nonsignum"
    insertbefore: BOF
    state: present

- name: set the gdm icon-theme to Papirus
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus'"
    state: present
  become_user: gdm

- name: set the gdm font to fira sans
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Fira Sans Regular 11'"
    state: present
  become_user: gdm

- name: set sleep-inactive-ac-timeout for {{ ansible_user_id }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "7200"
    state: present
  become_user: gdm

- name: set sleep-inactive-ac-type for {{ ansible_user_id }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'nothing'"
    state: present
  become_user: gdm

- name: set sleep-inactive-battery-timeout for {{ ansible_user_id }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
    value: "7200"
    state: present
  become_user: gdm

- name: set sleep-inactive-battery-type for {{ ansible_user_id }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
    value: "'nothing'"
    state: present
  become_user: gdm

- name: switch to xorg from wayland
  lineinfile:
    path: "/etc/gdm/custom.conf"
    regexp: "^#*WaylandEnable=false"
    line: "WaylandEnable=false"
    state: present
