- name: install dependencies
  package:
    name:
      - syncthing
      - code
      - evince
      - sxhkd
  tags:
    - packages

- name: install notable
  aur: name=notable-bin state=present
  when: ansible_distribution == "Archlinux"
  become_user: consul
  tags:
    - packages
