- name: clone notes for {{ user }}
  become_user: "{{ user }}"
  git:
    repo: git@gitlab.com:DictumMortuum/notes.git
    dest: "/home/{{ user }}/Notes"

- name: install notes cronjob sync for {{ user }}
  become_user: "{{ user }}"
  cron:
    name: "sync notes repo"
    minute: "10,30,50"
    job: "dotctl sync-repo /home/{{ user }}/Notes"
